FROM jenkins/ssh-agent:latest-jdk17

USER root

RUN apt-get update && apt-get install -y \
    git \
    rpm \
    build-essential \
    debhelper \
    devscripts \
    fakeroot \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
