FROM jenkins/ssh-agent:latest-jdk17

USER root

RUN apt-get update && apt-get install -y \
    git \
    rpm \
    build-essential \
    debhelper \
    devscripts \
    fakeroot \
    && rm -rf /var/lib/apt/lists/*
